-- liquibase formatted sql

CREATE TABLE USER_ACCOUNT (
    USER_ID                 BIGINT IDENTITY,
    EMAIL                   VARCHAR(255) NOT NULL,
    FIRST_NAME              VARCHAR(255) NOT NULL,
    LAST_NAME               VARCHAR(255) NOT NULL,
    PASSWORD                VARCHAR(255) NOT NULL,
    ROLE                    VARCHAR(255),
    EMAIL_VERIFIED BOOLEAN  BOOLEAN DEFAULT FALSE
);

CREATE TABLE REGISTRATION_TOKEN (
    ID                     BIGINT IDENTITY,
    TOKEN                  VARCHAR(255) NOT NULL,
    EMAIL                  VARCHAR(255) NOT NULL,
    EXPIRATION             DATE NOT NULL
);

CREATE TABLE BANKING_ACCOUNT (
    ACCOUNT_ID             BIGINT IDENTITY,
    MONEY                  FLOAT NOT NULL,
    INTEREST_RATE_PA       FLOAT NOT NULL,
    ACTIVE                 BOOLEAN DEFAULT TRUE,
    CURRENCY               VARCHAR(255) DEFAULT "EUR" NOT NULL,
    ACCOUNT_TYPE           VARCHAR(255) DEFAULT "CHECKING_ACCOUNT" NOT NULL

    FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT(USER_ID)
);

CREATE TABLE BANKING_TRANSACTION (
    TRANSACTION_ID          BIGINT IDENTITY,
    CREATION_TIME           DATE NOT NULL,
    AMOUNT                  FLOAT NOT NULL,
    DESCRIPTION             VARCHAR(255),
    SENDING                 BOOLEAN

    FOREIGN KEY (ACCOUNT_ID) REFERENCES USER_ACCOUNT(BANKING_ACCOUNT)
);
