###
POST http://localhost:8080/registration
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email",
    "firstName": "Stan",
    "lastName": "Gislason",
    "password": "password"
}

###
POST http://localhost:8080/registration/sendVerificationMail
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email"
}


###
GET http://localhost:8080/registration/verify?token=token

###
# @name login
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email",
    "password": "password"
}

@token = {{login.response.body.token}}

###
GET http://localhost:8080/user/refreshSesssions
Content-Type: application/json

###
POST http://localhost:8080/user/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email",
    "password": "password"
}