###
POST http://localhost:8080/registration
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email",
    "firstName": "Stan",
    "lastName": "Gislason",
    "password": "password"
}

###
POST http://localhost:8080/registration/sendVerificationMail
Content-Type: application/json

{
    "email": "stan.gislason@ethereal.email"
}


###
GET http://localhost:8080/registration/verify?token=token