name: BankingApp CI

on:
  workflow_dispatch: 
  push:
    branches: [ "main", "feature/*" ]
    paths: 
      - "bankingapp/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "bankingapp/**"

  
jobs:
  build_test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./bankingapp
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3.0.3
      with:
        directory: ./bankingapp
        ignore-maven-wrapper: true