name: BankingApp-UI CI

on:
  workflow_dispatch: 
  push:
    branches: [ "main", "feature/*" ]
    paths: 
      - "bankingapp-ui/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "bankingapp-ui/**"


jobs:
  build:

    defaults:
      run:
        working-directory: ./bankingapp-ui

    runs-on: ubuntu-latest
        
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./bankingapp-ui/package-lock.json
        registry-url: https://npm.pkg.github.com/

    - name: Install Dependencies
      run: |
        npm install -g @angular/cli 
        npm ci
        
    - name: Run tests
      run: ng test --code-coverage --watch=false

    - name: Linting Errors
      run: |
        npm run lint
        echo "# Test Coverage" >> $GITHUB_STEP_SUMMARY
        echo " \`\`\` " >> $GITHUB_STEP_SUMMARY
        cat "./coverage/bankingapp-ui/coverage.txt" >> $GITHUB_STEP_SUMMARY
        echo " \`\`\` " >> $GITHUB_STEP_SUMMARY

    - name: Run Cypress Tests
      run: |
        ng serve --configuration development &
        until $(curl --output /dev/null --silent --head --fail http://localhost:4200); do
          echo "Starting Angular application"
          sleep 5
        done
        npm run cypress:run
    
    - name: Grype security check
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
        grype dir:./node_modules --config ../.grype.yml